openapi: 3.0.3
info:
  title: TP Web INSA Rennes
  description: |-
    Intro au dev d'un back-end REST en Java avec Spring et OpenAPI
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
tags: # Some annotations used to document the route descriptions (optional)
  - name: todo
    description: Les todos
paths:
  /public/todo/hello:
    get:
      tags:
        - todo
      responses:
        '200':
          description: c'est bon
  /public/todo/todo:
    get:
      tags:
        - todo
      responses:
        '200':
          description: c'est bon
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    post:
      tags:
        - todo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: c'est bon
  /public/todo/todo/{id}:
    delete:
      tags:
        - todo
      parameters:
        - name: id
          in: path
          description: The identifier of the todo to delete
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
        description:
          type: string
        categories:
          type: array
          items:
            type: string
