openapi: 3.0.3
info:
  title: TP Web INSA Rennes
  description: |
    Introduction to REST back-end development in Java with Spring and OpenAPI
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: todo
    description: REST operations on Todos
paths:
  /public/todo/hello:
    get:
      tags:
        - todo
      responses:
        '200':
          description: c'est bon
  /public/todo/todo:
    get:
      tags:
        - todo
      responses:
        '200':
          description: c'est bon
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    post:
      tags:
        - tod
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true      
      responses:
        '200':
          description: c'est bon
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        categories:
          type: array
          items:
            type: string
            enum:
              - HIGH_PRIORITY
              - LOW_PRIORITY
              - WORK
              - ENTERTAINMENT
