openapi: 3.0.3
info:
  title: TP Web INSA Rennes
  description: |
    Introduction to REST back-end development in Java with Spring and OpenAPI
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v2
tags:
  - name: todo
    description: REST operations on Todos
  - name: todolist
    description: REST operations on Todo lists
paths:
  /private/todo/hello:
    get:
      security:
        - CookieAuth: []
      tags:
        - todo
      responses:
        '200':
          description: Success
  /private/todo/todo:
    get:
      security:
        - CookieAuth: []
      tags:
        - todo
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    post:
      security:
        - CookieAuth: []
      tags:
        - todo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    put:
      security:
        - CookieAuth: []
      tags:
        - todo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid ID supplied
  /private/todo/todo/{id}:
    patch:
      security:
        - CookieAuth: []
      tags:
        - todo
      parameters:
        - name: id
          in: path
          description: Identifier of the todo to patch
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: Success
        '400':
          description: Invalid ID supplied
    delete:
      security:
        - CookieAuth: []
      tags:
        - todo
      parameters:
        - name: id
          in: path
          description: Identifier of the todo to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied

  /private/todo/title:
    get:
      security:
        - CookieAuth: []
      tags:
        - todo
      parameters:
        - name: txt
          in: query
          description: Text fragment to search for in titles
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

  /private/todolist:
    post:
      tags:
        - todolist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NamedDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
  /private/todolist/addtodo:
    patch:
      description: Add a todo into a todo list (using a DTO to provide ids)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdsDTO'
        required: true
      tags:
        - todolist
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
  /private/todolist/{todoListId}/addtodo/{todoId}:
    patch:
      description: Add a todo into a todo list (using path variables to provide ids)
      parameters:
        - name: todoListId
          in: path
          description: Identifier of the todo list
          required: true
          schema:
            type: integer
            format: int64
        - name: todoId
          in: path
          description: Identifier of the todo
          required: true
          schema:
            type: integer
            format: int64
      tags:
        - todolist
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
  /public/user/new:
    post:
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Success
  /public/user/login:
    post:
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Success
  /private/user:
    get:
      tags:
        - user
      security:
        - CookieAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    Todo:
      type: object
      properties:
        type:
          type: string
          enum:
            - todo
            - spec
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        categories:
          type: array
          items:
            type: string
            enum:
              - HIGH_PRIORITY
              - LOW_PRIORITY
              - WORK
              - ENTERTAINMENT
    TodoList:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        owner:
          type: string
        todos:
          type: array
          items:
            $ref: '#/components/schemas/Todo'
    NamedDTO:
      type: object
      properties:
        name:
          type: string
    IdsDTO:
      type: object
      properties:
        todoListId:
          type: integer
          format: int64
        todoId:
          type: integer
          format: int64
    UserDTO:
      type: object
      properties:
        login:
          type: string
        pwd:
          type: string
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID
      description: Use a session cookie to authenticate (see /login).
